name: responsive_text
description: "A Flutter widget for responsive text with support for currency formatting, gradient effects, and text truncation"
version: 0.0.1
homepage: https://github.com/stephanekonan/responsive_text

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
